version: '3.8'

services:
  frontend:
    image: ashu111/bot-web-frontend:latest
    
    ports:
      - "3000:80"


  backend:
    image: ashu111/bot-web-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    


