name: CI/CD - Build & Deploy

on:
  push:
    branches:
      - main

jobs:
    backend:
        name: Build and push docker image
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: setup python
              uses: actions/setup-python@v2
              with:
                python-version: '3.11'

            - name: Install dependencies
              run: | 
                  python -m pip install --upgrade pip
                  pip install fastapi uvicorn docker python-dotenv


            - name: Build Docker image
              run: |
                  docker build -t ${{ secrets.DOCKER_USERNAME }}/bot-web-backend:${{ github.sha }} -f ./backend/Dockerfile ./backend
                  docker tag ${{ secrets.DOCKER_USERNAME }}/bot-web-backend:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/bot-web-backend:latest

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Push Docker image
              run: |
                  docker push ${{ secrets.DOCKER_USERNAME }}/bot-web-backend:${{ github.sha }}
                  docker push ${{ secrets.DOCKER_USERNAME }}/bot-web-backend:latest
    frontend:
        name: Build and push frontend image
        runs-on: ubuntu-latest          

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: setup node
              uses: actions/setup-node@v2
              with:
                  node-version: '16'

            - name: Install dependencies
              working-directory: ./frontend
              run: |
                  npm install

            - name: Build Docker image
              run: |
                  docker build -t ${{ secrets.DOCKER_USERNAME }}/bot-web-frontend:${{ github.sha }} -f ./frontend/Dockerfile ./frontend
                  docker tag ${{ secrets.DOCKER_USERNAME }}/bot-web-frontend:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/bot-web-frontend:latest

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Push Docker image
              run: |
                  docker push ${{ secrets.DOCKER_USERNAME }}/bot-web-frontend:${{ github.sha }}
                  docker push ${{ secrets.DOCKER_USERNAME }}/bot-web-frontend:latest

    deploy:
        name: Deploy to server
        runs-on: ubuntu-latest

        needs: [backend, frontend]

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Deploy to server
              run: |
                  echo $(curl -X POST http://test.ashu.devinit.in/deployee -H "X-API-KEY:${{ secrets.AUTH_TOKEN }}" )